// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebReverseEngineering.Models;

public partial class pessoa
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int id_pessoa { get; set; }

    [Required]
    [StringLength(50)]
    public string nome_pessoa { get; set; }

    [Column(TypeName = "int(3)")]
    public int idade_pessoa { get; set; }
}